// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bank: typeof import('./src/components/global/Bank.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    OpenInfo: typeof import('./src/components/OpenInfo.vue')['default']
    OpenInfo1: typeof import('./src/components/OpenInfo1.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabbar: typeof import('./src/components/Tabbar.vue')['default']
    VanDivider: typeof import('vant/es')['Divider']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
